name: Setup
description: ''

runs:
  using: composite

  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version-file: ./.nvmrc
        cache: npm
        cache-dependency-path: ./package-lock.json

    - name: Install dependencies
      run: npm ci
      shell: bash
